### ISSUE TITLE
Angular directive

### ISSUE THREAD

**Issue by ishabi** [fengyuanchen/viewerjs#1]
I really like your work on images! Awesome. Is there any plan to create Angular directive for Viewer.js? I have an Angular project and I like to use your plugin to display images. Please let me know.

Thank you

**Comment by fengyuanchen** [comment]
You can create an Angular wrapper for Viewer.js as [ngCropper](https://github.com/koorgoo/ngCropper).

**Comment by KennethMa** [comment]
@ishabi 
``` typescript
@Directive({
  selector: '[seeViewer]',
})
export class SeeViewerDirective {
  @HostListener('load', ['$event.target'])
  onLoad(element: HTMLElement) {
    const el = new Viewer(element);
  }
}
```

**Comment by Devaarth** [comment]
@KennethMa I am trying to Implement viewer.js in my current Angular 4 CLI based application . The problem is that when i create a fresh Angular 4 project from scratch and try to run viewer.js it is running fine but when I am trying similar things and copying the same code into my application(which has other functionalities as well) I am not able to run viewer.js.

Also there no console or build issue showing up so I am not able to debug my problem as well.
Any help will be appreciated 

Thanks

**Comment by marcusforsberg** [comment]
I'm kind of late to the party here, but for what it's worth, we've just released a really simply directive you can use to implement Viewer.js in Angular 6+: https://github.com/winteragency/ngx-viewer/ (@Devaarth)
