### ISSUE TITLE
image url  '&' become '&amp;'  is question

### ISSUE THREAD

**Issue by louieaa** [fengyuanchen/viewerjs#301]
Original image has '&' character in src.
The image src is then html escaped by viewerjs to '&'.
The transformed url is not correct and the image is not shown.

'&' character is valid in urls. It should not be replaced.

e.g:
www.example.com/image?a=1&b=2
will be transformed to
www.example.com/image?a=1&amp;b=2

question in 
viewerjs/src/js/render.js  use   escapeHTMLEntities  function
 this escapeHTMLEntities  function regular ：```/&(?!amp;|quot;|#39;|lt;|gt;)/g```
![Snipaste_2019-07-02_19-11-31](https://user-images.githubusercontent.com/42113246/60508537-52200580-9cfd-11e9-8bb8-665cdb37e663.png) 

img 
![Snipaste_2019-07-02_19-05-03](https://user-images.githubusercontent.com/42113246/60508154-6adbeb80-9cfc-11e9-8612-0cf9d56abdd7.png)
please fix this question

**Comment by freimuts** [comment]
The issue is on this line: [here](https://github.com/fengyuanchen/viewerjs/blob/b3b9d2fccc5ddf250c8cebb449926df5b91d2beb/src/js/render.js#L71) and lines 76, 78

Not sure why URL has to be escaped and what kind of security it increases, but changing these lines or using version 1.3.4 helped.

Breaking commit: [00771b70dde5cd07745dda30c445961e2d3e4289](https://github.com/fengyuanchen/viewerjs/commit/00771b70dde5cd07745dda30c445961e2d3e4289#diff-d747dffaf35b1e70bb6e45628b3525c2)

@fengyuanchen
